### ISSUE TITLE
24年7月导出7000个主题的经验

### ISSUE THREAD

**Issue by sidazhang123** [wbsabc/zsxq-spider#18]
该脚本很好的地方在于评论和星主回答提问都能导出，其他脚本貌似没有做到。
1、报topics NoneType错的，请自行加requests的重试。
![image](https://github.com/user-attachments/assets/940c8a75-d6df-4a88-ae6c-137b612a36c1)
2、数量如果很多，建议不要删除html和pic，并且将htmls数组用pickle存下来避免生成pdf出错浪费时间
DELETE_PICS_WHEN_DONE = False                      # 运行完毕后是否删除下载的图片
DELETE_HTML_WHEN_DONE = False                      # 运行完毕后是否删除生成的HTML
3、生成pdf报错 [WinError 206] 文件名或扩展名太长
由于一次传入html过多。可以分片生成pdf，再用工具拼接pdf。300个html测试是可以的。直接拼html再转pdf会丢失格式很难看。
4、start_url apixxx/v1.10改为v1.2

**Comment by gimsimon** [comment]
你好大佬请问爬完多组后账号是否有封禁的情况,

**Comment by sidazhang123** [comment]
> 你好大佬请问爬完多组后账号是否有封禁的情况,

只用了这一次，加上当天测试导出应不超过2w组，没有异常
