### ISSUE TITLE
感谢分享,我下载之后运行不起来,失效了吗?

### ISSUE THREAD

**Issue by eluotao** [wbsabc/zsxq-spider#2]
如题.

**Comment by wbsabc** [comment]
调查了一下，网站对User-Agent进行了校验，校验不通过会清除session。
已经做了更新，请下载最新版本代码重新尝试。
另外zsxq_access_token也变更了逻辑，比原来的长，记得复制全，如果失效了刷一下网页重新复制一遍。

爬虫会对网站性能造成一定影响，请勿频繁使用，在必要时合理使用，大家都是去学习知识的，体谅一下吴老板。
再次强调，不要随意传播知识星球里的内容，那是犯罪行为。
