### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Alfred212121** [wbsabc/zsxq-spider#3]
Traceback (most recent call last):
  File "C:\Users\duanh\Desktop\zsxq-spider-master\crawl.py", line 262, in <module>
    make_pdf(get_data(url))
  File "C:\Users\duanh\Desktop\zsxq-spider-master\crawl.py", line 60, in get_data
    for topic in json.loads(f.read()).get('resp_data').get('topics'):
TypeError: 'NoneType' object is not iterable

**Comment by d8899p** [comment]
'NoneType' object is not iterable我也出现了这个问题请问您解决了嘛

**Comment by Timzhouyes** [comment]
+1 一样的问题……

**Comment by wbsabc** [comment]
调查了一下，网站对User-Agent进行了校验，校验不通过会清除session。
已经做了更新，请下载最新版本代码重新尝试。
另外zsxq_access_token也变更了逻辑，比原来的长，记得复制全，如果失效了刷一下网页重新复制一遍。

爬虫会对网站性能造成一定影响，请勿频繁使用，在必要时合理使用，大家都是去学习知识的，体谅一下吴老板。
再次强调，不要随意传播知识星球里的内容，那是犯罪行为。
