### ISSUE TITLE
请教"TypeError: 'NoneType' object is not iterable"怎么解决呢？

### ISSUE THREAD

**Issue by sara961** [wbsabc/zsxq-spider#4]
Traceback (most recent call last):
  File "crawl.py", line 264, in <module>
    make_pdf(get_data(url))
  File "crawl.py", line 62, in get_data
    for topic in json.loads(f.read()).get('resp_data').get('topics'):
TypeError: 'NoneType' object is not iterable

**Comment by wbsabc** [comment]
使用最新版代码，修改USER_AGENT，确保和登录时的一致。
