### ISSUE TITLE
报错了，不清楚哪里出了问题

### ISSUE THREAD

**Issue by cfvgbhnj** [wbsabc/zsxq-spider#5]
Traceback (most recent call last):
  File "D:\py program\zsxq-spider-master\crawl.py", line 262, in <module>
    make_pdf(get_data(url))
  File "D:\py program\zsxq-spider-master\crawl.py", line 60, in get_data
    for topic in json.loads(f.read()).get('resp_data').get('topics'):
TypeError: 'NoneType' object is not iterable

**Comment by wbsabc** [comment]
使用最新版代码，修改USER_AGENT，确保和登录时的一致。

**Comment by cfvgbhnj** [comment]
> 使用最新版本代码，修改USER_AGENT，确保和登录时的一致。

Traceback (most recent call last):
  File "D:\py program\zsxq-spider-master\crawl.py", line 263, in <module>
    make_pdf(get_data(url))
  File "D:\py program\zsxq-spider-master\crawl.py", line 61, in get_data
    for topic in json.loads(f.read()).get('resp_data').get('topics'):
TypeError: 'NoneType' object is not iterable

还是不行

**Comment by wbsabc** [comment]
> 使用最新版本代码，修改USER_AGENT，确保和登录时的一致。
> 
> Traceback (most recent call last):
> File "D:\py program\zsxq-spider-master\crawl.py", line 263, in 
> make_pdf(get_data(url))
> File "D:\py program\zsxq-spider-master\crawl.py", line 61, in get_data
> for topic in json.loads(f.read()).get('resp_data').get('topics'):
> TypeError: 'NoneType' object is not iterable
> 还是不行

我试了一下应该是没问题的。
ZSXQ_ACCESS_TOKEN和USER_AGENT一定要设置成和登录时一致的再运行，不然校验失败一次之后就会清空session，这个你可以在运行完之后回到浏览器刷新页面再看看是不是仍处于登录状态。
GROUP_ID改成你已经关注的知识星球的ID，在URL里就可以找到。
