### ISSUE TITLE
按步骤操作没生成成功

### ISSUE THREAD

**Issue by manyhelp** [wbsabc/zsxq-spider#6]
信息: 用提供的模式无法找到文件。
电子书生成成功！

没找到PDF

**Comment by wbsabc** [comment]
wkhtmltox安装并加入环境变量了吗？

**Comment by manyhelp** [comment]
加了的

**Comment by manyhelp** [comment]
重启下电脑好了。能生成PDF，但是PDF里的图片不显示

**Comment by manyhelp** [comment]
次数太多，封号了。要控制频率

**Comment by wbsabc** [comment]
新版本wkhtmltopdf写入图片好像有点问题，刚才修改了一下代码。
增加了请求之间sleep参数，先这样手动控制频率吧。
还是要合理使用避免封号...
