### ISSUE TITLE
 电子书生成失败！

### ISSUE THREAD

**Issue by curiousmind-z** [wbsabc/zsxq-spider#9]
请问如何处理
<bound method Response.json of <Response [200]>>
电子书生成失败！

**Comment by wbsabc** [comment]
确认以下操作是否完成：
安装 wkhtmltox，https://wkhtmltopdf.org/downloads.html。安装后将 bin 目录加入到环境变量。
另外之前有人反馈Mac里生成PDF有问题，Windows是可以的。
